export interface MalariaApp {
  name: string;
  category: string;
  developer: string;
  description: string;
  countries: string;
  funders: string;
  url: string;
}

export const malariaApps: MalariaApp[] = [
  { name: "DHIS2", category: "Health Information System", developer: "University of Oslo / HISP", description: "Open-source health management information platform used by 80+ countries for aggregate and individual-level data collection, analysis, and reporting.", countries: "Nigeria, 80+ countries", funders: "Norad, PEPFAR, Global Fund, Gavi", url: "https://dhis2.org" },
  { name: "CommCare", category: "Mobile Data Collection", developer: "Dimagi", description: "Open-source mobile platform for frontline workers enabling case management, data collection, and decision support at community level.", countries: "Nigeria, 60+ countries", funders: "USAID, Gates Foundation, DFID", url: "https://dimagi.com/commcare" },
  { name: "Audere", category: "AI Diagnostics", developer: "Audere", description: "AI-powered rapid diagnostic test reader using smartphone cameras to interpret mRDT results with 96.8% accuracy.", countries: "Nigeria, India, Kenya", funders: "Gates Foundation, USAID", url: "https://audere.org" },
  { name: "OpenMalaria", category: "Modelling & Simulation", developer: "Swiss TPH", description: "Individual-based stochastic simulation platform for modelling malaria epidemiology and evaluating intervention strategies.", countries: "Global (research)", funders: "Swiss TPH, Gates Foundation", url: "https://github.com/SwissTPH/openmalaria" },
  { name: "EMOD", category: "Modelling & Simulation", developer: "Institute for Disease Modeling (IDM)", description: "Epidemiological MODeling software for simulating malaria transmission dynamics, vector ecology, and intervention impact.", countries: "Global (research)", funders: "Gates Foundation, IDM", url: "https://idmod.org/tools" },
  { name: "Malaria Atlas Project (MAP)", category: "Geospatial & Mapping", developer: "University of Oxford / Telethon Kids", description: "Global database of georeferenced malaria prevalence surveys and high-resolution risk maps used for strategic planning.", countries: "Global", funders: "Gates Foundation, Wellcome Trust", url: "https://malariaatlas.org" },
  { name: "mSupply", category: "Supply Chain", developer: "The mSupply Foundation", description: "Open-source pharmaceutical supply chain management system for inventory, ordering, distribution, and cold chain monitoring.", countries: "25+ countries", funders: "Global Fund, UNICEF, UNFPA", url: "https://msupply.foundation" },
  { name: "OpenLMIS", category: "Supply Chain", developer: "OpenLMIS Community", description: "Open-source logistics management information system designed for low-resource health supply chains.", countries: "15+ countries", funders: "USAID, Rockefeller Foundation, Gates Foundation", url: "https://openlmis.org" },
  { name: "SORMAS", category: "Surveillance", developer: "Helmholtz Centre for Infection Research", description: "Surveillance Outbreak Response Management and Analysis System for real-time disease surveillance and outbreak management.", countries: "Nigeria, Ghana, Germany, France", funders: "BMZ, GIZ, WHO", url: "https://sormas.org" },
  { name: "VectorCam", category: "Entomology", developer: "Johns Hopkins University", description: "AI-powered smartphone application for automated identification of mosquito species from photographs to support entomological surveillance.", countries: "Research phase", funders: "NIH, Gates Foundation", url: "https://vectorcam.org" },
  { name: "Sproxil MAS", category: "Product Authentication", developer: "Sproxil Inc.", description: "Mobile Authentication Service enabling consumers to verify medicine authenticity via SMS or WhatsApp using scratch-off PIN codes.", countries: "Nigeria, India, Kenya, Ghana", funders: "USAID, Global Fund, Private sector", url: "https://sproxil.com" },
  { name: "ODK (Open Data Kit)", category: "Mobile Data Collection", developer: "ODK Community", description: "Open-source suite of tools for mobile data collection, form design, and data aggregation used widely in public health surveys.", countries: "Global", funders: "Gates Foundation, Google, USAID", url: "https://getodk.org" },
  { name: "KoboToolbox", category: "Mobile Data Collection", developer: "Harvard Humanitarian Initiative / OCHA", description: "Free open-source tool for mobile data collection in humanitarian and development contexts with offline capability.", countries: "Global", funders: "OCHA, USAID, Harvard", url: "https://kobotoolbox.org" },
  { name: "SurveyCTO", category: "Mobile Data Collection", developer: "Dobility Inc.", description: "Enterprise mobile data collection platform with advanced features for randomization, encryption, and quality control.", countries: "Global", funders: "Commercial + research grants", url: "https://surveycto.com" },
  { name: "PowerBI for Health", category: "Analytics & Visualization", developer: "Microsoft", description: "Business intelligence dashboards adapted for health programme monitoring with interactive visualizations and real-time data.", countries: "Global", funders: "Microsoft Philanthropies", url: "https://powerbi.microsoft.com" },
  { name: "Tableau Public Health", category: "Analytics & Visualization", developer: "Tableau / Salesforce", description: "Interactive data visualization platform used by WHO, CDC, and national malaria programmes for dashboard creation.", countries: "Global", funders: "Tableau Foundation", url: "https://tableau.com" },
  { name: "R Malaria Packages", category: "Modelling & Simulation", developer: "R Community / Imperial College", description: "Suite of R packages (malariasimulation, malariaAtlas, Individual) for malaria transmission modelling and data analysis.", countries: "Global (research)", funders: "Gates Foundation, Wellcome Trust", url: "https://mrc-ide.github.io/malariasimulation" },
  { name: "iHRIS", category: "Health Information System", developer: "IntraHealth International", description: "Open-source human resources information system for health workforce planning, tracking, and management.", countries: "30+ countries", funders: "USAID, WHO, PEPFAR", url: "https://ihris.org" },
  { name: "OpenMRS", category: "Health Information System", developer: "OpenMRS Community", description: "Open-source electronic medical record system designed for low-resource settings with modular architecture.", countries: "40+ countries", funders: "Gates Foundation, PEPFAR, Regenstrief", url: "https://openmrs.org" },
  { name: "RapidPro", category: "Communication & Messaging", developer: "UNICEF / Nyaruka", description: "Open-source platform for interactive messaging via SMS, WhatsApp, and voice for health communication campaigns.", countries: "60+ countries", funders: "UNICEF, USAID", url: "https://rapidpro.io" },
  { name: "Viamo (VOTO)", category: "Communication & Messaging", developer: "Viamo", description: "Mobile engagement platform using IVR, SMS, and data collection for health behaviour change communication at scale.", countries: "20+ countries", funders: "USAID, Gates Foundation, DFID", url: "https://viamo.io" },
  { name: "mTrac", category: "Surveillance", developer: "UNICEF Uganda / MOH", description: "Mobile-based disease surveillance and health commodity tracking system integrated with DHIS2 for real-time reporting.", countries: "Uganda, adapted elsewhere", funders: "UNICEF, WHO", url: "https://mtrac.ug" },
  { name: "EpiCollect5", category: "Mobile Data Collection", developer: "Imperial College London", description: "Free mobile data collection tool for epidemiological studies with GPS, photo, and barcode capture capabilities.", countries: "Global", funders: "Wellcome Trust, Imperial College", url: "https://five.epicollect.net" },
  { name: "AccessMod", category: "Geospatial & Mapping", developer: "WHO / University of Geneva", description: "WHO tool for modelling physical accessibility to health facilities considering terrain, transport, and population distribution.", countries: "Global", funders: "WHO, Swiss government", url: "https://accessmod.org" },
  { name: "QGIS Health Plugin", category: "Geospatial & Mapping", developer: "QGIS Community", description: "Open-source GIS platform with health-specific plugins for spatial analysis, mapping, and epidemiological visualization.", countries: "Global", funders: "Open source community", url: "https://qgis.org" },
  { name: "HealthMap", category: "Surveillance", developer: "Boston Children's Hospital", description: "Global disease surveillance platform aggregating online data sources for real-time outbreak monitoring and alerts.", countries: "Global", funders: "Google.org, Skoll Foundation", url: "https://healthmap.org" },
  { name: "Medic Mobile (CHT)", category: "Community Health", developer: "Medic", description: "Community Health Toolkit (CHT) — open-source platform for community health worker apps with offline-first architecture.", countries: "25+ countries", funders: "Gates Foundation, USAID, Skoll", url: "https://medic.org" },
  { name: "D-tree International", category: "Community Health", developer: "D-tree International", description: "Digital health decision support tools for community health workers providing clinical protocols and referral pathways.", countries: "Tanzania, Malawi, Zambia", funders: "USAID, UNICEF, Gates Foundation", url: "https://dtree.org" },
  { name: "mPedigree", category: "Product Authentication", developer: "mPedigree", description: "Mobile verification platform for consumers to check medicine authenticity using codes and smartphone scanning.", countries: "Ghana, Nigeria, Kenya", funders: "Private sector, USAID", url: "https://mpedigree.com" },
  { name: "PharmaSecure", category: "Product Authentication", developer: "PharmaSecure", description: "Medicine authentication and supply chain intelligence platform using unique codes and AI-powered analytics.", countries: "India, Nigeria", funders: "Gates Foundation, Private sector", url: "https://pharmasecure.com" },
  { name: "OpenSRP", category: "Community Health", developer: "ona.io / OpenSRP Community", description: "Open Smart Register Platform for digitizing health registers used by frontline workers for maternal, child, and malaria care.", countries: "Indonesia, Pakistan, Bangladesh, Zambia", funders: "WHO, Gates Foundation, USAID", url: "https://opensrp.io" },
  { name: "Reveal (DiGITHAL)", category: "Geospatial & Mapping", developer: "Akros / ona.io", description: "Spatial intelligence platform for planning and monitoring IRS campaigns, ITN distribution, and mass drug administration.", countries: "Zambia, Namibia, Thailand, Senegal", funders: "Gates Foundation, Clinton Health Access", url: "https://revealprecision.com" },
  { name: "Climate Data Store (CDS)", category: "Climate & Environment", developer: "ECMWF / Copernicus", description: "Climate reanalysis and forecast data platform providing temperature, rainfall, and humidity data for malaria risk prediction.", countries: "Global", funders: "EU Copernicus Programme", url: "https://cds.climate.copernicus.eu" },
  { name: "Google Earth Engine", category: "Climate & Environment", developer: "Google", description: "Cloud computing platform for geospatial analysis at scale, used for mapping environmental malaria risk factors.", countries: "Global", funders: "Google Philanthropies", url: "https://earthengine.google.com" },
  { name: "IASO", category: "Health Information System", developer: "Bluesquare", description: "Geospatial data management platform for health facility registries, boundary management, and micro-planning.", countries: "DRC, Cameroon, Burundi", funders: "Global Fund, Gavi, BMGF", url: "https://bluesquare.org" },
  { name: "Tupange / mHealth Kenya", category: "Communication & Messaging", developer: "Jhpiego / MOH Kenya", description: "mHealth platform for sending targeted health messages to pregnant women and caregivers about malaria prevention.", countries: "Kenya", funders: "USAID, Gates Foundation", url: "https://jhpiego.org" },
  { name: "MalariaGEN", category: "Genomics & Research", developer: "Wellcome Sanger Institute / Oxford", description: "Global network generating and sharing genomic data on malaria parasites and mosquito vectors to track drug and insecticide resistance.", countries: "30+ endemic countries", funders: "Wellcome Trust, Gates Foundation, MRC", url: "https://malariagen.net" },
  { name: "WWARN", category: "Genomics & Research", developer: "WorldWide Antimalarial Resistance Network", description: "Global platform for pooled analysis of antimalarial drug efficacy data to detect and map emerging drug resistance.", countries: "Global", funders: "Gates Foundation, Wellcome Trust", url: "https://wwarn.org" },
  { name: "Malariaspot", category: "AI Diagnostics", developer: "Universidad Politécnica de Madrid", description: "Gamified crowdsourcing and AI platform for analysing digitized blood smear images to detect malaria parasites.", countries: "Research / Global", funders: "EU, Spanish government", url: "https://malariaspot.org" },
  { name: "EasyDiagnosis", category: "AI Diagnostics", developer: "Various research groups", description: "Smartphone-based microscopy adapter and AI algorithm for automated malaria parasite detection from thick blood smears.", countries: "Research phase", funders: "NIH, Wellcome Trust", url: "#" },
  { name: "Logistimo", category: "Supply Chain", developer: "Logistimo", description: "Cloud-based supply chain management platform for last-mile health commodity visibility, temperature monitoring, and demand forecasting.", countries: "India, East Africa", funders: "USAID, Rockefeller Foundation", url: "https://logistimo.com" },
  { name: "mHero", category: "Communication & Messaging", developer: "IntraHealth / UNICEF", description: "Two-way health worker communication platform integrating with iHRIS and RapidPro for real-time data exchange.", countries: "Liberia, Guinea, Sierra Leone", funders: "USAID, UNICEF, CDC", url: "https://mhero.org" },
  { name: "Bahmni", category: "Health Information System", developer: "Bahmni / ThoughtWorks", description: "Open-source hospital information system combining EMR, lab management, and pharmacy modules for low-resource hospitals.", countries: "India, Bangladesh, Sierra Leone", funders: "ThoughtWorks, JSS", url: "https://bahmni.org" },
];

export const appCategories = Array.from(new Set(malariaApps.map((a) => a.category))).sort();
